# Generated by Django 3.2.16 on 2023-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
