# Generated by Django 3.2.16 on 2023-06-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
