# Generated by Django 3.2.16 on 2023-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_choice_voters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollOption',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='voter',
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
